<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Identity.Domain\Identity.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Accounts\Queries\" />
    <Folder Include="Authentication\Commands\" />
  </ItemGroup>
</Project>
