<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="MailKit" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Minio" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Scrutor" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Identity.Application\Identity.Application.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Persistence\Migrations\" />
    </ItemGroup>
</Project>
